"""add_reject_reason_to_photos

Revision ID: b1d87e7498ad
Revises: 620c17140cdd
Create Date: 2026-02-27 20:59:19.984951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d87e7498ad'
down_revision: Union[str, Sequence[str], None] = '620c17140cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('photos', sa.Column('reject_reason', sa.String(length=32), nullable=True))
    # заполняем NULL status значением 'raw' перед NOT NULL constraint
    op.execute("UPDATE photos SET status = 'raw' WHERE status IS NULL")
    op.alter_column('photos', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default='raw',
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('photos', 'reject_reason')
    # ### end Alembic commands ###
